package com.own.core.service;
import com.own.core.service.IBaseService;
import com.own.base.entity.UserDO;
/**
 *com.own.core.service.IUserServices.java
 *2018-04-27 10:26:50
 * This was class generated by ant velocity
 */
public interface IUserService extends IBaseService<UserDO,java.lang.String>{

}
