package com.own.dao;
import com.own.common.base.dao.IBaseMapper;
import com.own.base.entity.UserDO;

/**
 *com.own.dao.IUserMapper.java
 *2018-04-27 10:26:50
 * This was class generated by ant velocity
 */
public interface IUserMapper extends IBaseMapper<UserDO,java.lang.String> {
 
}


